# https://travis-ci.org/soimort/you-get
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
before_install: pip install flake8
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2'* ]]; then flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics; fi
script: make test
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/43cd57826e88ed8f2152
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
