#!/usr/bin/env python3

import os, sys
__path__ = os.path.dirname(os.path.realpath(__file__))
__srcdir__ = 'src'
sys.path.insert(1, os.path.join(__path__, __srcdir__))
from you_get.extractor import main

if __name__ == '__main__':
    main()
